### ISSUE TITLE
how to get the whole dataset

### ISSUE THREAD

**Issue by shinsonwu** [erenolg/IBBTraffic#1]
"from the original website of IBB ()"：
could you pls give the details website ？

**Comment by erenolg** [comment]
https://data.ibb.gov.tr/dataset/hourly-traffic-density-data-set

You can use this website to access original data (without preprocessing), I will also include them into repo soon.

**Comment by shinsonwu** [comment]
> https://data.ibb.gov.tr/dataset/hourly-traffic-density-data-set
> 
> You can use this website to access original data (without preprocessing), I will also include them into repo soon.

Thank you for your timely response. I truly appreciate the outstanding work you've done and for making it open source.
